# Generated by Django 3.1.12 on 2021-06-26 21:15

from django.db import migrations, models
import websites.models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author_picture',
            field=models.ImageField(upload_to=websites.models._get_review_dir_path),
        ),
        migrations.AlterField(
            model_name='websitehost',
            name='picture',
            field=models.ImageField(upload_to=websites.models._get_photo_dir_path),
        ),
        migrations.AlterField(
            model_name='websitephoto',
            name='image',
            field=models.ImageField(upload_to=websites.models._get_photo_dir_path),
        ),
    ]
