# Generated by Django 3.1.13 on 2021-10-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eroouser',
            name='username',
            field=models.CharField(default='defaultname', max_length=32),
            preserve_default=False,
        ),
    ]
