# Generated by Django 3.1.13 on 2021-10-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_eroouser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='eroouser',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eroouser',
            name='spacename',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
