# Generated by Django 3.1.13 on 2021-10-14 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_start_date', models.DateField()),
                ('_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BookingSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.housing')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRateModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_percent', models.BooleanField(default=True)),
                ('is_discount', models.BooleanField(default=True)),
                ('minimal_number_of_days', models.IntegerField()),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookingseason')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('extra_guest_price', models.ManyToManyField(to='bookings.BookingPrice')),
                ('periods', models.ManyToManyField(to='bookings.BookingPeriod')),
                ('seasons', models.ManyToManyField(to='bookings.BookingSeason')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPriceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.housing')),
            ],
        ),
        migrations.AddField(
            model_name='bookingprice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookingpricecategory'),
        ),
        migrations.AddField(
            model_name='bookingperiod',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookingseason'),
        ),
        migrations.CreateModel(
            name='BookingFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_per_night', models.BooleanField()),
                ('is_per_guest', models.BooleanField()),
                ('guest_price', models.ManyToManyField(to='bookings.BookingPrice')),
                ('periods', models.ManyToManyField(to='bookings.BookingPeriod')),
                ('seasons', models.ManyToManyField(to='bookings.BookingSeason')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.housing')),
            ],
        ),
    ]
