# Generated by Django 3.1.13 on 2021-11-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='housing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.housing'),
        ),
        migrations.AlterField(
            model_name='bookingperiod',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='bookings.bookingseason'),
        ),
        migrations.AlterField(
            model_name='bookingprice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookingpricecategory'),
        ),
        migrations.AlterField(
            model_name='bookingpricecategory',
            name='housing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.housing'),
        ),
        migrations.AlterField(
            model_name='bookingratemodifier',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookingseason'),
        ),
        migrations.AlterField(
            model_name='bookingseason',
            name='housing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.housing'),
        ),
    ]
